src/main/java/com/github/packageurl/PackageURL.java, src/test/java/com/github/packageurl/PackageURLTest.java
Added convenience class (StandardTypes) that provides statically typed constants for PackageURL 'type's.
=> Added convenience class (StandardTypes) for PackageURL 'type's

src/main/java/com/github/packageurl/PackageURL.java, src/test/java/com/github/packageurl/PackageURLTest.java
Although for NPM according to https://docs.npmjs.com/cli/v7/configuring-npm/package-json#name
> New packages must not have uppercase letters in the name.
some old NPM packages exist that do have uppercase letters in their names
For example
This package
https://www.npmjs.com/package/Base64/v/1.0.0
Is different to this package
https://www.npmjs.com/package/base64/v/1.0.0
However at the moment they have the same Package URL  i.e.
`pkg:npm/base64@1.0.0`
This PR stops the NPM namespace and name validations from lower-casing so that instead we end up with the Package URLs
`pkg:npm/Base64@1.0.0`
`pkg:npm/base64@1.0.0`
=> Account for NPM being case-sensitive

src/main/java/com/github/packageurl/PackageURL.java, src/test/resources/test-suite-data.json
Fixes https://github.com/package-url/packageurl-java/issues/91. More context on [this comment](https://github.com/package-url/packageurl-java/pull/90#issuecomment-1771409666).
=> URI encode/decode in conformance with RFC 3986

src/main/java/com/github/packageurl/PackageURL.java, src/test/java/com/github/packageurl/PackageURLTest.java
Removed unnecessary cache of canonicalized form leading to unexpected behavior. Updated unit tests.
Fixes #89
=> Removed unnecessary cache of canonicalized form

src/main/java/com/github/packageurl/PackageURL.java, src/main/java/com/github/packageurl/PackageURLBuilder.java, src/test/java/com/github/packageurl/PackageURLBuilderTest.java
=> Allow builder to be fully editable

src/main/java/com/github/packageurl/MalformedPackageURLException.java, src/main/java/com/github/packageurl/PackageURL.java
Add constructors to `MalformedPackageURLException` to propagate the underlying cause.
=> Add constructors to `MalformedPackageURLException`

src/main/java/com/github/packageurl/PackageURL.java
Remove the `scheme` field and replace it with a `SCHEME` constant as its impossible to create a `PackageURL` with a different `scheme`. This should not change the public API.
It was previously the case that parsing a purl could produce different `URI` representations internally based on the number of slashes present after the scheme colon in the input. For example, a purl with the canonical form `pkg:generic/name` when input starting with `pkg:`, `pkg:/`, and `pkg://` will produce three different `URI` representations. By normalizing the input to contain a single `'/'`, as in `pkg:/generic/name`, we obtain a valid hierarchical `URI` with all five standard components `[scheme:][//authority][path][?query][#fragment]` properly parsed. For the `URI` to be a valid purl, `scheme:` must be …
=> Fix URI creation

src/main/java/com/github/packageurl/PackageURL.java
There were places in the code where code was duplicated or could return different results based on the locale. Duplicate code was moved to new methods. The locale-specic lowercase method were replaced by an ASCII-specific lowecase method.
=> Fix case of various components

src/main/java/com/github/packageurl/PackageURL.java, src/test/java/com/github/packageurl/PackageURLBuilderTest.java, src/test/java/com/github/packageurl/PackageURLTest.java
The spec says that keys are case insensitive and that the canonical form is lowercase. This means that the parser should accept any case, but treat all variations as the same key.
=> Allow non-lowercase qualifier keys

src/main/java/com/github/packageurl/PackageURLBuilder.java, src/test/java/com/github/packageurl/PackageURLBuilderTest.java
The return type of the method `PackageURLBuilder::getQualifiers` should be an interface, such as `Map`, rather than the implementation `TreeMap`. This aligns with the return type of the method
`PackageURL::getQualifiers`.
Also, make the return types of this method match the return types of
`PackageURL::getQualifiers`.
Note that this a potentially breaking API change.
=> Make `PackageURLBuilder::getQualifiers` return `Map`

src/main/java/com/github/packageurl/PackageURLBuilder.java, src/test/java/com/github/packageurl/PackageURLBuilderTest.java
This allows passing a map of qualifiers directly to `PackageURLBuilder` instead of having to call `withQualifier` for every key-value pair. This aligns with the `PackageURL` constructor which allows passing such a map.
=> feat: add `withQualifiers(Map)` to `PackageURLBuilder`

src/main/java/com/github/packageurl/PackageURL.java
* Fix potential null pointers
* Use `String::replace()` instead of `replaceAll` for single characters
* Use `isEmpty` which can be more efficient
* Remove exception which is not thrown
* Make `StandardTypes` constructor private
=> fix: correct issues with `PackageURL`

src/main/java/com/github/packageurl/PackageURL.java
* Remove need to use regex and split on single character
* Remove check for `null` or empty since its checked before
=> Simplify `parsePath`

src/main/java/com/github/packageurl/PackageURL.java, src/main/java/com/github/packageurl/PackageURLBuilder.java, src/test/java/com/github/packageurl/PackageURLBuilderTest.java
This is useful if you have an existing purl and need to modify one or more of its components.
This differs from `PackageURL::toBuilder` in that it doesn't require the direct use of the `PackageURL` constructor which conflicts with the builder pattern.
=> Allow creating a builder from a pre-existing purl

src/main/java/com/github/packageurl/PackageURL.java
In the `PackageURL::validatePath(String, boolean)` method, the `boolean` parameter value is always `true`, so remove it.
=> Simplify `PackageURL::validatePath(String, boolean)`

pom.xml, src/test/java/com/github/packageurl/PackageURLBuilderTest.java, src/test/java/com/github/packageurl/PackageURLTest.java
Migrates tests to JUnit 5:
- Most of the migration is performed using the [JUnit Jupiter best practices](https://docs.openrewrite.org/recipes/java/testing/junit5/junit5bestpractices) OpenRewrite recipe (d6769dec8cfaae1e5c72e0bd8ca4911d7fd57c1f). This step consists in adding the `rewrite-maven-plugin` to `pluginManagement`:
```xml
<plugin>
<groupId>org.openrewrite.maven</groupId>
<artifactId>rewrite-maven-plugin</artifactId>
<version>6.3.0</version>
<dependencies>
<dependency>
<groupId>org.openrewrite.recipe</groupId>
<artifactId>rewrite-testing-frameworks</artifactId>
<version>3.4.0</version>
</dependency>
</dependencies>
</plugin>
```
and running:
```sh
mvn rewrite:run -Drewrite.activeRecipes=org.openrewrite.java.testing.junit5.JUnit5BestPractices
```
- The few compilation errors that …
=> Migrates tests to JUnit 5

src/main/java/com/github/packageurl/PackageURL.java, src/test/java/com/github/packageurl/PackageURLTest.java
The methods `uriEncode` and `uriDecode` did not properly handle percent-encoding. In particular, `uriEncode` didn't properly output two uppercase hex digits and `urlDecode` did not properly handle non-ASCII characters.
Aditionally, if no percent-encoding was performed, these methods will now return the original string.
Fixes #150
Closes #153
Fixes #154
=> Fix URL encoding and decoding

pom.xml
As jspecify is just a compile-time annotation, I believe this should be marked as an optional dependency. Other examples of this:
- https://github.com/google/google-java-format/blob/ccb56c79b0bf4cec457e06f1156a0a0234ca576d/core/pom.xml#L44-L48
- https://github.com/google/jimfs/blob/68dcc63d5386ad015611400f72778217c981f40c/jimfs/pom.xml#L63-L67
- https://github.com/google/turbine/blob/a2aa5bee245643d1939c16c3c2e9f67ab51da5e7/pom.xml#L81-L85
=> fix: make jspecify a compile time/optional dependency

bnd.bnd, pom.xml, src/main/java/com/github/packageurl/package-info.java, src/main/java/com/github/packageurl/validator/package-info.java
Adds [BND Maven Plugins](https://github.com/bndtools/bnd/blob/master/maven-plugins/README.md) to:
- Generate an OSGi bundle descriptor (`MANIFEST.MF`).
- Generate a JPMS bundle descriptor.
- Check for binary compatibility between releases.
The binary compatibility check is implemented by adding the `bnd-baseline-maven-plugin` that checks if the version increment is compatible with the change type: 
- `MICRO`—only annotations added to the public API
- `MINOR`—only binary compatible changes
- `MAJOR`—binary incompatible changes
Fixes #96
=> Adds BND Maven Plugins

pom.xml, src/test/java/com/github/packageurl/PackageURLBuilderTest.java, src/test/java/com/github/packageurl/PackageURLTest.java, src/test/java/com/github/packageurl/PurlParameters.java, src/test/resources/components-constructor-only.json, src/test/resources/custom-suite.json, src/test/resources/string-constructor-only.json, src/test/resources/type-namespace-constructor-only.json
Replaces many test cases with parameterized tests that take their data from JSON files.
=> feat(tests): Additional parametrization of tests

src/main/java/com/github/packageurl/PackageURL.java
* Use single character append instead of string append
* Avoid `StringBuilder::setLength` for qualifiers
* Qualifier keys are already lowercase
=> feat: improve `toString()`

pom.xml, src/headers/java.txt, src/headers/xml.txt, src/main/java/com/github/packageurl/MalformedPackageURLException.java, src/main/java/com/github/packageurl/PackageURL.java, src/main/java/com/github/packageurl/PackageURLBuilder.java, src/main/java/com/github/packageurl/validator/PackageURL.java, src/test/java/com/github/packageurl/PackageURLBuilderTest.java, src/test/java/com/github/packageurl/PackageURLTest.java, src/test/java/com/github/packageurl/PurlParameters.java
This PR adds a Spotless configuration that uses:
- The [`palantir-java-format`](https://github.com/palantir/palantir-java-format) formatter for Java files.
- The [`sort-pom`](https://github.com/Ekryd/sortpom) formatter for the POM file.
This PR contains two commits:
- febb1236643e82fbd1b35f01c069dac94312729b is a manual change the POM file.
- fc1972e51307a57e1fa0b6fe8079793a4a09a7ab was generated by calling:
```sh
mvn spotless:apply
```
and should be easy to reproduce.
Closes #183
=> style: add Spotless formatter configuration

src/main/java/com/github/packageurl/PackageURL.java
Don't bother partitioning array
Skip bytes already in the decode buffer
=> fix: improve performance of encode and decode

src/main/java/com/github/packageurl/MalformedPackageURLException.java, src/main/java/com/github/packageurl/PackageURL.java, src/main/java/com/github/packageurl/PackageURLBuilder.java, src/main/java/com/github/packageurl/package-info.java, src/main/java/com/github/packageurl/validator/PackageURL.java, src/main/java/com/github/packageurl/validator/package-info.java, src/test/java/com/github/packageurl/PackageURLBuilderTest.java, src/test/java/com/github/packageurl/PackageURLTest.java
Add some missing javadoc.
Fix some method visibility issues and remove use of deprecated methods from code.
=> fix: add missing `@deprecated` and `@since` to javadoc

src/main/java/com/github/packageurl/PackageURL.java
`PackageURL` is an immutable class, so the fields should be `final`. This is achieved by moving the parsing code into the constructor. This fixes `@NullMarked` fields must be initialized.
=> fix: make fields final

pom.xml, src/main/java/com/github/packageurl/PackageURL.java, src/test/java/com/github/packageurl/PercentEncodingBenchmark.java
This adds a small benchmark for percent encoding/decoding algorithms. You can run it with:
```
mvn -Pbenchmark
```
To pass arguments to JMH use `-Djmh.args="<arguments>"`.
=> feat: add a small benchmark for percent encoding decoding

src/main/java/com/github/packageurl/PackageURL.java, src/test/java/com/github/packageurl/PercentEncodingBenchmark.java
This PR:
- Fixes a bug in the benchmark initialization. The `decodedData` array was **not** the decoded version of `encodedData`.
- Tries to figure out the best `baseline`. I suspect that the simplest version:
```java
blackhole.consume(new String(decodedData[i].getBytes(UTF_8), UTF_8));
```
could be super-optimized by the compiler to something like:
```java
blackhole.consume(decodedData[i]);
```
- Adds a benchmark for the `toLowerCase()` method.
The current benchmark results are:
```
Benchmark                               (nonAsciiProb)  Mode  Cnt    Score    Error  Units
PercentEncodingBenchmark.baseline                    0  avgt    5   37.273 ±  0.128  us/op
PercentEncodingBenchmark.baseline                  0.1  avgt    5   36.887 ±  0.185  us/op
PercentEncodingBenchmark.baseline …
```
=> feat: Improve benchmark

src/main/java/com/github/packageurl/utils/StringUtil.java, src/test/java/com/github/packageurl/utils/StringUtilBenchmark.java
Since in practice most Package URLs don't have any percent encoded characters, this PR optimizes the `percentEncode/percentDecode` methods by:
- Always testing if encoding/decoding is needed. If it is not needed, the methods return the argument unmodified.
- Improving the performance of `isUnreserved`, since profiling shows that this is the most important method for the performance of `percentEncode`.
=> feat: Improve encoding/decoding performance for ASCII strings

pom.xml
Disable `ErrorProne` reporting on `generated-test-sources`.
=> fix: do not report ErrorProne results on generated-test-sources

src/test/java/com/github/packageurl/PackageURLBuilderTest.java, src/test/java/com/github/packageurl/PackageURLTest.java, src/test/java/com/github/packageurl/internal/StringUtilTest.java
* Remove `public` modifier
* Remove exceptions which are not thrown
* Print test description if there is an unexpected failure
=> fix: fix some minor issues with tests

pom.xml
This makes the build cross-platform and fixes execution on, e.g., Windows.
=> fix: use separator properties when running JMH
